force-app/main/default/objects/BiField__c/BiField__c.object-meta.xml
<CustomObject>
    <label>BI Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIField_Column__c/BIField_Column__c.object-meta.xml
<CustomObject>
    <label>BI Field/Column</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BI Field/Column Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Fields/Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIField_Column__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Column</label>
    <referenceTo>Column__c</referenceTo>
    <relationshipLabel>BI Fields</relationshipLabel>
    <relationshipName>BI_Field_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BiProject__c/BiProject__c.object-meta.xml
<CustomObject>
    <label>BI Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BiView__c/BiView__c.object-meta.xml
<CustomObject>
    <label>BI View</label>
    <nameField>
        <label>View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BiView__c/fields/BiWorkbook__c.field-meta.xml
<CustomField>
    <fullName>BiWorkbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BiWorkbook</label>
    <referenceTo>BiWorkbook__c</referenceTo>
    <relationshipName>BiView</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BiWorkbook__c/BiWorkbook__c.object-meta.xml
<CustomObject>
    <label>BI Workbook</label>
    <nameField>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Workbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BiWorkbook__c/fields/BiProject__c.field-meta.xml
<CustomField>
    <fullName>BiProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>BiProject__c</referenceTo>
    <relationshipLabel>Workbooks</relationshipLabel>
    <relationshipName>BiWorkbook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Column__c/Column__c.object-meta.xml
<CustomObject>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Column__c/fields/Table__c.field-meta.xml
<CustomField>
    <fullName>Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Table</label>
    <referenceTo>Table__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Database__c/Database__c.object-meta.xml
<CustomObject>
    <label>Database</label>
    <nameField>
        <label>Database Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Databases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schema__c/Schema__c.object-meta.xml
<CustomObject>
    <label>Schema</label>
    <nameField>
        <label>Schema Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schema__c/fields/Database__c.field-meta.xml
<CustomField>
    <fullName>Database__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Database</label>
    <referenceTo>Database__c</referenceTo>
    <relationshipLabel>Schemas</relationshipLabel>
    <relationshipName>Schema</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Table__c/Table__c.object-meta.xml
<CustomObject>
    <label>Table</label>
    <nameField>
        <label>Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Table__c/fields/Schema__c.field-meta.xml
<CustomField>
    <fullName>Schema__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schema</label>
    <referenceTo>Schema__c</referenceTo>
    <relationshipLabel>Tables</relationshipLabel>
    <relationshipName>Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestImpactAnalysis.cls
@isTest
public class TestImpactAnalysis {
    
    @isTest
    static void shouldGetColumnImpactAnalysis() { // TODO Please move column logic in Lineage class to a new "ImpactAnalysis" class and move this test to a "TestImpactAnalysis" class.
        Database__c db = TestDataFactory.createDatabase('Database');
		Schema__c sch = TestDataFactory.createSchema(db, 'Schema');
		Table__c tbl = TestDataFactory.createTable(sch, 'Table');
		Column__c col = TestDataFactory.createColumn(tbl, 'Column');
        BiProject__c p = TestDataFactory.createBiProject('Project');
		BiWorkbook__c wb = TestDataFactory.createBiWorkbook(p, 'Workbook');
		BiView__c v = TestDataFactory.createBiView(wb, 'View');
		BiField__c f = TestDataFactory.createBiField(v, 'Field');
        BiField_Column__c fc = TestDataFactory.createColumnBifield(f, col);    
        Test.startTest();
    	String json = ImpactAnalysis.getImpactData(col.Id);
        Test.stopTest();
        System.assert(json != null);
    }
    @isTest
    static void shouldThrowExceptionOnUnsupportedObjectType() {
        Boolean failed;
		Account a = new Account(Name='Example');
        insert a;
        
        Test.startTest();
        try {
            String json = ImpactAnalysis.getImpactData(a.Id);
			failed = false;
        } catch (IllegalArgumentException e) {
            failed = true;
        }
        Test.stopTest();
        
        System.assert(true);
    }
}