force-app/main/default/objects/BiField__c/BiField__c.object-meta.xml
<CustomObject>
    <label>BI Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIField_Column__c/BIField_Column__c.object-meta.xml
<CustomObject>
    <label>BI Field/Column</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BI Field/Column Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Fields/Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIField_Column__c/fields/BI_Field__c.field-meta.xml
<CustomField>
    <fullName>BI_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Field</label>
    <referenceTo>BiField__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>BI_Field_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIField_Column__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Column</label>
    <referenceTo>Column__c</referenceTo>
    <relationshipLabel>BI Fields</relationshipLabel>
    <relationshipName>BI_Field_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Column__c/Column__c.object-meta.xml
<CustomObject>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Column__c/fields/Table__c.field-meta.xml
<CustomField>
    <fullName>Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Table</label>
    <referenceTo>Table__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Table__c/Table__c.object-meta.xml
<CustomObject>
    <label>Table</label>
    <nameField>
        <label>Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ImpactAnalysis.cls
public with sharing
class ImpactAnalysis {
	public ImpactAnalysis() {

	}

	@AuraEnabled(Cacheable = true)
	public static string getImpactData(Id recordId){
		String sObjectType=String.valueOf(recordId.getSobjectType());     
		String jsonData;
		ImpactAnalysis impact=new ImpactAnalysis();
		switch on sObjectType{
		when 'Column__c','ydc__Column__c'{

			Column__c columnData = [SELECT Id, Name,Table__r.Name, (SELECT Id, Name,Bi_Field__r.Name,Bi_Field__r.Id FROM BI_Field_Column__r) FROM Column__c WHERE Id =: recordId];
			//Create a columnrecord
			ParentData columnRecord = new ParentData(columnData.Name,null,impact.reportUrl(recordId,'Column__c'),'Column','Related to');
			//Loop on BiField_Column
			for(BIField_Column__c columnFieldData: columnData.BI_Field_Column__r) {

				columnRecord.children.add(new ChildData(columnFieldData.BI_Field__r.Name,'Top Level',impact.reportUrl(columnFieldData.BI_Field__r.Id,'BIField__c'),'BIField','Related to'));

			}

			//Get the Json data
			jsonData = JSON.serialize(columnRecord);

		}

		}

		return jsonData;
	}

	public String reportUrl(Id id,String objName){
		String url=URL.getSalesforceBaseUrl().toExternalForm()+'/lightning/r/'+objName+'/'+id+'/view';

		return url;
	}
}