force-app/main/default/objects/BiField__c/BiField__c.object-meta.xml
<CustomObject>
    <label>BI Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIField_Column__c/BIField_Column__c.object-meta.xml
<CustomObject>
    <label>BI Field/Column</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BI Field/Column Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Fields/Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIField_Column__c/fields/BI_Field__c.field-meta.xml
<CustomField>
    <fullName>BI_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Field</label>
    <referenceTo>BiField__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>BI_Field_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIField_Column__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Column</label>
    <referenceTo>Column__c</referenceTo>
    <relationshipLabel>BI Fields</relationshipLabel>
    <relationshipName>BI_Field_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Column__c/Column__c.object-meta.xml
<CustomObject>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Lineage.cls
public with sharing
class Lineage {
	public Lineage() {

	}

	@AuraEnabled(Cacheable = true)
	public static string getLineageData(Id recordId){
		String sObjectType=String.valueOf(recordId.getSobjectType());     
		String jsonData;
		Lineage lineage=new Lineage();
		switch on sObjectType{
		when 'BiField__c','ydc__BiField__c'{
			BiField__c fieldData = [SELECT Id, Name, (SELECT Id, Name,Column__r.Name,Column__r.Id FROM BI_Field_Column__r) FROM BiField__c WHERE Id =: recordId];
			//Create a fieldRecord
			ParentData fieldRecord = new ParentData(fieldData.Name,null,lineage.reportUrl(recordId,'BiField__c'),'BiField','Related to');
			//Loop on BiField_Column
			for(BiField_Column__c fieldColumnData: fieldData.BI_Field_Column__r) {

				fieldRecord.children.add(new ChildData(fieldColumnData.Column__r.Name,'Top Level',lineage.reportUrl(fieldColumnData.Column__r.Id,'Column__c'),'Column','Related to'));

			}

			//Get the Json data
			jsonData = JSON.serialize(fieldRecord);

		}

		}

		return jsonData;
	}

	public String reportUrl(Id id,String objName){
		String url=URL.getSalesforceBaseUrl().toExternalForm()+'/lightning/r/'+objName+'/'+id+'/view';

		return url;
	}

}