force-app/main/default/objects/BiField__c/BiField__c.object-meta.xml
<CustomObject>
    <label>BI Field</label>
    <nameField>
        <label>Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Fields</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BiField__c/fields/BI_View__c.field-meta.xml
<CustomField>
    <fullName>BI_View__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI View</label>
    <referenceTo>BiView__c</referenceTo>
    <relationshipLabel>BI Fields</relationshipLabel>
    <relationshipName>BI_Fields</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIField_Column__c/BIField_Column__c.object-meta.xml
<CustomObject>
    <label>BI Field/Column</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>BI Field/Column Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BI Fields/Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BIField_Column__c/fields/BI_Field__c.field-meta.xml
<CustomField>
    <fullName>BI_Field__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BI Field</label>
    <referenceTo>BiField__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>BI_Field_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BIField_Column__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Column</label>
    <referenceTo>Column__c</referenceTo>
    <relationshipLabel>BI Fields</relationshipLabel>
    <relationshipName>BI_Field_Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BiProject__c/BiProject__c.object-meta.xml
<CustomObject>
    <label>BI Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BiView__c/BiView__c.object-meta.xml
<CustomObject>
    <label>BI View</label>
    <nameField>
        <label>View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BiView__c/fields/BiWorkbook__c.field-meta.xml
<CustomField>
    <fullName>BiWorkbook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BiWorkbook</label>
    <referenceTo>BiWorkbook__c</referenceTo>
    <relationshipName>BiView</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BiWorkbook__c/BiWorkbook__c.object-meta.xml
<CustomObject>
    <label>BI Workbook</label>
    <nameField>
        <label>Workbook Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BI Workbooks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BiWorkbook__c/fields/BiProject__c.field-meta.xml
<CustomField>
    <fullName>BiProject__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>BiProject__c</referenceTo>
    <relationshipLabel>Workbooks</relationshipLabel>
    <relationshipName>BiWorkbook</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Column__c/Column__c.object-meta.xml
<CustomObject>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Column__c/fields/Table__c.field-meta.xml
<CustomField>
    <fullName>Table__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Table</label>
    <referenceTo>Table__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>Column</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Database__c/Database__c.object-meta.xml
<CustomObject>
    <label>Database</label>
    <nameField>
        <label>Database Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Databases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schema__c/Schema__c.object-meta.xml
<CustomObject>
    <label>Schema</label>
    <nameField>
        <label>Schema Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schemas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Schema__c/fields/Database__c.field-meta.xml
<CustomField>
    <fullName>Database__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Database</label>
    <referenceTo>Database__c</referenceTo>
    <relationshipLabel>Schemas</relationshipLabel>
    <relationshipName>Schema</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Table__c/Table__c.object-meta.xml
<CustomObject>
    <label>Table</label>
    <nameField>
        <label>Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Table__c/fields/Schema__c.field-meta.xml
<CustomField>
    <fullName>Schema__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Schema</label>
    <referenceTo>Schema__c</referenceTo>
    <relationshipLabel>Tables</relationshipLabel>
    <relationshipName>Table</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
    
    public static Database__c createDatabase(String name) {
        Database__c obj = new Database__c();
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static Schema__c createSchema(Database__c db, String name) {
        Schema__c obj = new Schema__c();
        obj.Database__c = db.Id;
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static Table__c createTable(Schema__c sch, String name) {
        Table__c obj = new Table__c();
        obj.Schema__c = sch.Id;
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static Column__c createColumn(Table__c tbl, String name) {
        Column__c obj = new Column__c();
        obj.Table__c = tbl.Id;
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static BiProject__c createBiProject(String name) {
        BiProject__c obj = new BiProject__c();
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static BiWorkbook__c createBiWorkbook(BiProject__c p, String name) {
        BiWorkbook__c obj = new BiWorkbook__c();
        obj.BiProject__c = p.Id;
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static BiView__c createBiView(BiWorkbook__c wb, String name) {
        BiView__c obj = new BiView__c();
        obj.BiWorkbook__c = wb.Id;
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static BiField__c createBiField(BiView__c v, String name) {
        BiField__c obj = new BiField__c();
        obj.BI_View__c = v.Id;
        obj.Name = name;
        insert obj;
        return obj;
    }
    
    public static BiField_Column__c createBiFieldColumn(Column__c c, BiField__c f) {
        BiField_Column__c obj = new BiField_Column__c();
        obj.Column__c = c.Id;
        obj.BI_Field__c = f.Id;
        insert obj;
        return obj;
    }
     public static BiField_Column__c createColumnBifield( BiField__c f, Column__c c) {
        BiField_Column__c obj = new BiField_Column__c();
        obj.Column__c = c.Id;
        obj.BI_Field__c = f.Id;
        insert obj;
        return obj;
    }

}