force-app/main/default/objects/Column__c/Column__c.object-meta.xml
<CustomObject>
    <label>Column</label>
    <nameField>
        <label>Column Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Quality_Rule_Column__c/Data_Quality_Rule_Column__c.object-meta.xml
<CustomObject>
    <label>Data Quality Rule Column</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Data Quality Rule Column Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Quality Rule Column</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Quality_Rule_Column__c/fields/Column__c.field-meta.xml
<CustomField>
    <fullName>Column__c</fullName>
    <label>Column</label>
    <referenceTo>Column__c</referenceTo>
    <relationshipLabel>Data Quality Rules</relationshipLabel>
    <relationshipName>Data_Quality_Rule_Column</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Data_Quality_Rule_Column__c/fields/Data_Quality_Rule__c.field-meta.xml
<CustomField>
    <fullName>Data_Quality_Rule__c</fullName>
    <label>Data Quality Rule</label>
    <referenceTo>Data_Quality_Rules__c</referenceTo>
    <relationshipLabel>Columns</relationshipLabel>
    <relationshipName>Data_Quality_Rule_Column</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DataQualityRuleController.cls
public without sharing class DataQualityRuleController {
    
    @AuraEnabled
    public static void addColumnsToDataQualityRule(List<String> columnIds, String dataQualityRuleId) {
        System.debug('Data quality rule id is ' + dataQualityRuleId);
        System.debug('Column ids are' + columnIds);
        if (columnIds != null && columnIds.size() > 0) {
	        saveDataQualityRuleColumns(columnIds, dataQualityRuleId);            
        }
    }
        
    private static void saveDataQualityRuleColumns(List<Id> ids, String dataRequestId) {                        
        List<Data_Quality_Rule_Column__c> drqcs = new List<Data_Quality_Rule_Column__c>();
        
        for (Id id : ids) {
            String sObjectType = String.valueOf(id.getSobjectType());
            switch on sObjectType {
                when 'Column__c', 'ydc__Column__c' {
                    addColumn(drqcs, id, dataRequestId);
                }
            }
        }

        if (
            !Schema.sObjectType.Data_Quality_Rule_Column__c.isCreateable()
        ) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: Insufficient Write Access'));
        }
        
        insert drqcs;
    }
    
    private static void addColumn(List<Data_Quality_Rule_Column__c> drqcs, Id column, String dataQualityRuleId) {
        Data_Quality_Rule_Column__c drqc = new Data_Quality_Rule_Column__c();
        drqc.Data_Quality_Rule__c = dataQualityRuleId;
        drqc.Column__c = column;
        drqcs.add(drqc);
    }
    
    private static void addColumns(List<Data_Quality_Rule_Column__c> drqcs, List<Column__c> columns, String dataQualityRuleId) {
        if (columns != null) {
            for (Column__c column : columns) {
                addColumn(drqcs, column.Id, dataQualityRuleId);
            }
        }
    }
    
}